version: '3'

services:

  pygmy:
    image: amit19/pygmy
    restart: always
    build: .
    # ports:
    #  - "9119:9119"
    volumes:
     - .:/pygmy
    command: gunicorn --log-file /var/log/pygmy/error_logs.log --access-logfile /var/log/pygmy/acclogs.log --log-level DEBUG --bind 0.0.0.0:9119 --workers 2 pygmy.rest.wsgi:app

  pygmyui:
    image: amit19/pygmy
    restart: always
    build: .
    ports:
     - "10101:8000"
    links:
      - pygmy
    environment:
      - PYGMY_API_ADDRESS=pygmy
    command: sh -c "cd pygmyui && gunicorn --log-file /var/log/pygmy/uierror_logs.log --access-logfile /var/log/pygmy/uiacclogs.log --bind 0.0.0.0:8000 --workers 2 pygmyui.wsgi && cd .."
    depends_on:
      - pygmy

volumes:
  pgdata:
